parameters:
  - name: rust
    default: stable                
  - name: release
    type: boolean
    default: true
  - name: artifactName
    default: target
  - name: builds
    type: object
    default:
    - target: x86_64-unknown-linux-gnu 
      name: x86_64_unknown_linux_gnu
      pre-steps: [] 
    # - target: x86_64-apple-darwin
    #   name: x86_64_apple_darwin
    #   pre-steps: []
    # - target: x86_64-pc-windows-msvc
    #   name: x86_64_pc_windows_msvc
    #   pre-steps: []

jobs:
- ${{ each build in parameters['builds'] }}:
  - ${{ if contains(build.target, 'linux') }}:
    - template: ../jobs/cargo-build.yml
      parameters:
        rust: ${{ parameters['rust'] }}
        job_name: ${{ build.name }}
        job_displayName: "target ${{ build.target }}" 
        job_pool:
          vmImage: ubuntu-20.04
        release: ${{ parameters['release'] }}
        target: "${{ build.target }}"
        job_pre-steps: ${{ build['pre-steps'] }}
        job_post-steps:
          - bash: |
              echo ${{Build.SourceBranch}}
              REPO_BASE_NAME="$(basename $(Build.Repository.Name))"
              echo "##vso[task.setvariable variable=repo_base_name]$REPO_BASE_NAME"
          - template: ../steps/artifacts.yml
            parameters:
              archiveName: "$(REPO_BASE_NAME) - ${{ build.target }}"
              artifactName: ${{ parameters['artifactName'] }}

  - ${{ if contains(build.target, 'apple') }}:
    - template: ../jobs/cargo-build.yml
      parameters:
        rust: ${{ parameters['rust'] }}
        job_name: ${{ build.name }}
        job_displayName: "target ${{ build.target }}"
        job_pool:
          vmImage: macOS-10.15
        release: ${{ parameters['release'] }} 
        target: "${{ build.target }}"
        job_pre-steps: ${{ build['pre-steps'] }}
        job_post-steps:
          - bash: |
              REPO_BASE_NAME="$(basename $(Build.Repository.Name))"
              echo "##vso[task.setvariable variable=repo_base_name]$REPO_BASE_NAME"
          - template: ../steps/artifacts.yml
            parameters:
              archiveName: "$(REPO_BASE_NAME) - ${{ build.target }}"
              artifactName: ${{ parameters['artifactName'] }}

  - ${{ if contains(build.target, 'windows') }}:
    - template: ../jobs/cargo-build.yml
      parameters:
        rust: ${{ parameters['rust'] }}
        job_name: ${{ build.name }}
        job_displayName: "target ${{ build.target }}"
        job_pool:
          vmImage: vs2017-win2016
        release: ${{ parameters['release'] }} 
        target: "${{ build.target }}"
        job_pre-steps: ${{ build['pre-steps'] }}
        job_post-steps:
          - bash: |
              REPO_BASE_NAME="$(basename $(Build.Repository.Name))"
              echo "##vso[task.setvariable variable=repo_base_name]$REPO_BASE_NAME"
          - template: ../steps/artifacts.yml
            parameters:
              archiveName: "$(REPO_BASE_NAME) - ${{ build.target }}"
              artifactName: ${{ parameters['artifactName'] }}
