name: Rust

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: work dir
      run: pwd
    - name: ls dir
      run: ls -l src/config/hooks.test.yaml
    # - uses: actions/checkout@v3
    # - name: Build
    #   run: cargo build --verbose
    # - name: Run tests
    #   run: cargo test --verbose
