name: Rust

on:
  push:
    branches: 
    - "test"
    - "main"
  pull_request:
    branches: 
    - "test" 
    - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: show dir
      run: command -v /home/runner/work/rusthook/rusthook/src/command/test.sh
    - name: Run tests
      run: cargo test --verbose
